CREATE TYPE GRAPH_ENTITY_STATE AS ENUM ('CONCEPT', 'ACTIVE', 'REJECTED', 'REVOKED', 'DELETED');
CREATE TYPE HISTORY_TYPE AS ENUM (
    'STATE_TRANSITION',
    'ENTITY_REQUEST_CREATED', 'ENTITY_REQUEST_APPROVED', 'ENTITY_REQUEST_REJECTED',
    'COMPLAINT_CREATED', 'COMPLAINT_APPROVED', 'COMPLAINT_REJECTED'
);

CREATE TABLE HISTORY (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    created timestamp NOT NULL DEFAULT current_timestamp,
    author VARCHAR(50) NOT NULL,
    type HISTORY_TYPE NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    previous_state GRAPH_ENTITY_STATE,
    current_state GRAPH_ENTITY_STATE,
    related_entity_id VARCHAR(50)
);
