CREATE TYPE COMPLAINT_STATE AS ENUM ( 'ADMIN_DECISION', 'APPROVED', 'REJECTED', 'ENTITY_MODIFIED' );
CREATE TYPE ENTITY_TYPE AS ENUM ('PERSON', 'COMPANY', 'RELATIONSHIP');

CREATE TABLE COMPLAINT (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    entity_id VARCHAR(50) NOT NULL,
    entity_type ENTITY_TYPE NOT NULL,
    author VARCHAR(50) NOT NULL,
    assignee VARCHAR(50),
    title VARCHAR(100) NOT NULL,
    explanation VARCHAR(2000) NOT NULL,
    state COMPLAINT_STATE NOT NULL,
    created timestamp NOT NULL DEFAULT current_timestamp,
    task_url BYTEA,
    ip_address BYTEA NOT NULL
);
